### ISSUE TITLE
Add a requirements.txt file

### ISSUE THREAD

**Issue by jorisschellekens** [swasher/printMES#2]
Adding a `requirements.txt` file allows other devs to easily setup this repository with the dependencies needed.

Creating a `requirements.txt` file is as easy as running `pip freeze > requirements.txt`.

**Comment by swasher** [comment]
Thank you for suggestion and for your great `borb` project!
This project under heavy development, so it has many disadvantages. 
Currently, project use `pipenv` as package manager.

**Comment by swasher** [comment]
added `requirements.txt` (for current development state)
